### ISSUE TITLE
Default Date From seems to fail

### ISSUE THREAD

**Issue by Mentioum** [PostHog/posthog-plugin-migrator3000#15]
# What happened
## Error from Posthog Cloud Plugin Output
```
2022-06-30 13:11:00.304 UTC | PLUGIN | ERROR | Error: Unable to determine the lower timestamp bound for the export automatically. Please specify a 'dateFrom' value.     at Proxy.meta.global.initTimestampsAndCursor (/code/plugin-server/dist/worker/vm/upgrades/historical-export/export-historical-events.js:164:23)     at Object.exec (/code/plugin-server/dist/worker/vm/upgrades/historical-export/export-historical-events.js:79:31)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (node:internal/process/task_queues:96:5)     at async runPluginTask (/code/plugin-server/dist/worker/plugins/run.js:88:20)     at async /code/plugin-server/dist/worker/worker.js:49:49     at async /code/plugin-server/node_modules/@posthog/piscina/dist/src/worker.js:149:26
-- | -- | -- | --
```
## Field implies empty is fine
![image](https://user-images.githubusercontent.com/748170/176675083-5dc9b3da-362f-4751-be6c-72a71649fa5d.png)

# Expectation
It exports all events if no date is given (as per field help text)

**Comment by Mentioum** [comment]
Also when putting an arbitrary date a long time ago you get this error:
![image](https://user-images.githubusercontent.com/748170/176694939-ad607f71-1a2d-4ed7-94ca-c52752b9deb4.png)

It should probably do a query to find the first event after the time and then do chunks of events from that point forward.

**Comment by lsmith77** [comment]
I guess a simpler work-around could also be to just use a date before Posthog even existed? ie.  `2020-01-01`
